module.exports = [{
    name: '아메리카',
    subMenus: [{
        name: '괌'
    }, {
        name: '뉴욕'
    }, {
        name: '라스베가스'
    }, {
        name: '사이판'
    }, {
        name: '샌프란시스코'
    }, {
        name: '하와이'
    }]
}, {
    name: '아시아',
    subMenus: [{
        name: '다낭'
    }, {
        name: '대만'
    }, {
        name: '도쿄'
    }, {
        name: '라오스'
    }, {
        name: '마카오'
    }, {
        name: '몽골'
    }, {
        name: '발리'
    }, {
        name: '방콩'
    }, {
        name: '보라카이'
    }, {
        name: '상해'
    }, {
        name: '세부'
    }, {
        name: '시엠립'
    }, {
        name: '싱가폴'
    }, {
        name: '오사카'
    }, {
        name: '오키나와'
    }, {
        name: '치앙마이'
    }, {
        name: '코타키나발루'
    }, {
        name: '쿠알라룸푸르'
    }, {
        name: '푸켓'
    }, {
        name: '훗카이도'
    }, {
        name: '홍콩'
    }, {
        name: '후쿠오카'
    }]
}, {
    name: '유럽',
    subMenus: [{
        name: '런던'
    }, {
        name: '로마'
    }, {
        name: '마드리드'
    }, {
        name: '바르셀로나'
    }, {
        name: '베네치아'
    }, {
        name: '유레일패스'
    }, {
        name: '인터라켄'
    }, {
        name: '파리'
    }, {
        name: '피렌체'
    }]
}, {
    name: '오세아니아',
    subMenus: [{
        name: '골드코스트'
    }, {
        name: '뉴질랜드'
    }, {
        name: '다윈'
    }, {
        name: '멜버른'
    }, {
        name: '브리즈번'
    }, {
        name: '시드니'
    }, {
        name: '애들레이드'
    }, {
        name: '울룰루'
    }, {
        name: '타즈매니아'
    }, {
        name: '퍼스'
    }]
}, {
    name: '국내',
    subMenus: [{
        name: '강원'
    }, {
        name: '서울'
    }, {
        name: '순천'
    }, {
        name: '전라'
    }, {
        name: '제주'
    }, {
        name: '충청'
    }, {
        name: '통영'
    }]
}];