module.exports = [{
    name: '아메리카',
    subMenus: [{
        id: 'Guam',
        name: '괌'
    }, {
        id: 'Newyork',
        name: '뉴욕'
    }, {
        id: 'LasVegas',
        name: '라스베가스'
    }, {
        id: 'Saipan',
        name: '사이판'
    }, {
        id: 'San-Francisco',
        name: '샌프란시스코'
    }, {
        id: 'Hawaii',
        name: '하와이'
    }]
}, {
    name: '아시아',
    subMenus: [{
        id: 'Danang',
        name: '다낭'
    }, {
        id: 'Taiwan',
        name: '대만'
    }, {
        id: 'Tokyo',
        name: '도쿄'
    }, {
        id: 'Laos',
        name: '라오스'
    }, {
        id: 'Macau',
        name: '마카오'
    }, {
        id: 'Mongolia',
        name: '몽골'
    }, {
        id: 'Bali',
        name: '발리'
    }, {
        id: 'BangKok',
        name: '방콕'
    }, {
        id: 'Boracay',
        name: '보라카이'
    }, {
        id: 'Shanghai',
        name: '상해'
    }, {
        id: 'Cebu',
        name: '세부'
    }, {
        id: 'Siemreap',
        name: '시엠립'
    }, {
        id: 'Singapore',
        name: '싱가폴'
    }, {
        id: 'Osaka',
        name: '오사카'
    }, {
        id: 'Okinawa',
        name: '오키나와'
    }, {
        id: 'Chiang-Mai',
        name: '치앙마이'
    }, {
        id: 'Kotakinabalu',
        name: '코타키나발루'
    }, {
        id: 'Kualalumpur',
        name: '쿠알라룸푸르'
    }, {
        id: 'Phuket',
        name: '푸켓'
    }, {
        id: 'Hokkaido',
        name: '훗카이도'
    }, {
        id: 'HongKong',
        name: '홍콩'
    }, {
        id: 'Fukuoka',
        name: '후쿠오카'
    }]
}, {
    name: '유럽',
    subMenus: [{
        id: 'London',
        name: '런던'
    }, {
        id: 'Rome',
        name: '로마'
    }, {
        id: 'Madrid',
        name: '마드리드'
    }, {
        id: 'Barcelona',
        name: '바르셀로나'
    }, {
        id: 'Venice',
        name: '베네치아'
    }, {
        id: 'eurail',
        name: '유레일패스'
    }, {
        id: 'Interlaken',
        name: '인터라켄'
    }, {
        id: 'Paris',
        name: '파리'
    }, {
        id: 'Florence',
        name: '피렌체'
    }]
}, {
    name: '오세아니아',
    subMenus: [{
        id: 'Gold-Coast',
        name: '골드코스트'
    }, {
        id: 'NewZealand',
        name: '뉴질랜드'
    }, {
        id: 'darwin',
        name: '다윈'
    }, {
        id: 'Melbourne',
        name: '멜버른'
    }, {
        id: 'Brisbane',
        name: '브리즈번'
    }, {
        id: 'Sydney',
        name: '시드니'
    }, {
        id: 'adelaide',
        name: '애들레이드'
    }, {
        id: 'uluru',
        name: '울룰루'
    }, {
        id: 'tasmania',
        name: '타즈매니아'
    }, {
        id: 'perth',
        name: '퍼스'
    }]
}, {
    name: '국내',
    subMenus: [{
        id: 'gangwon',
        name: '강원'
    }, {
        id: 'gyeonggi',
        name: '경기'
    }, {
        id: 'gyeongsang',
        name: '경상'
    }, {
        id: 'daejeon',
        name: '대전'
    }, {
        id: 'seoul',
        name: '서울'
    }, {
        id: 'suncheon',
        name: '순천'
    }, {
        id: 'incheon',
        name: '인천'
    }, {
        id: 'jeolla',
        name: '전라'
    }, {
        id: 'Jeju',
        name: '제주'
    }, {
        id: 'Chungcheong',
        name: '충청'
    }, {
        id: 'tongyeong',
        name: '통영'
    }]
}];